import { useState } from 'react';
import type { ScenarioOut, ScenarioComparison, AssessmentSummary, ScenarioModification } from '../../api/contracts';
import { useSession } from '../../hooks/useSession';
import { Panel, Resource, Rows, Value, RecordForm, ActionButton, useResource, useSave, ErrorNotice } from '../../components/platform/shared';
import { Note } from '../../components/ui/common';
export default function Scenarios({id}: {id:string}) {
  const query=useResource<ScenarioOut[]>('/factories/'+id+'/scenarios'), baselines=useResource<AssessmentSummary[]>('/factories/'+id+'/assessments?limit=100'),save=useSave(),{can}=useSession(),[changes,setChanges]=useState<ScenarioModification[]>([]),[selected,setSelected]=useState<ScenarioOut|null>(null),[comparison,setComparison]=useState<ScenarioComparison|null>(null),[error,setError]=useState<unknown>();
  return <><Panel title="Scenario lab"><Resource query={query}>{rows=><Rows rows={rows} columns={['name','description','created_at']} caption="Scenarios" onOpen={setSelected}/>}</Resource>{selected&&<><Value value={selected.modifications}/>{can('assessment:run')&&<ActionButton onClick={async()=>setComparison(await save<ScenarioComparison>('/scenarios/'+selected.id+'/run'))}>Run {selected.name}</ActionButton>}</>}{comparison&&<><h3>Baseline compared with scenario</h3><Value value={{baseline:comparison.baseline,result:comparison.result,delta_tco2e:comparison.delta_tco2e,delta_pct:comparison.delta_pct,unsupported:comparison.unsupported}}/></>}<Note>Only the engine calculates scenario changes. The baseline snapshot remains unchanged; scenario assessments are excluded from peer benchmarks.</Note></Panel>{can('assessment:run')&&<Panel title="Build a scenario"><RecordForm schema="ScenarioModification" fields={{kind:{},value:{},target_key:{help:'Required for recycled materials and fuel switching. Use a reference factor key.'},replacement_key:{help:'Required for fuel switching.'}}} submit="Add change to scenario" onSubmit={async body=>{setChanges([...changes,body as ScenarioModification]);}}/>{changes.map((change,i)=><div className="platform-extracted" key={i}><Value value={change}/><button className="text-button" onClick={()=>setChanges(changes.filter((_,j)=>i!==j))}>Remove change</button></div>)}<RecordForm schema="ScenarioCreate" fields={{name:{},description:{type:'textarea'},baseline_assessment_id:{required:true,options:baselines.data?.filter(a=>a.is_baseline).map(a=>({value:a.id,label:(a.label||a.id)+' · '+a.created_at}))||[]}}} submit="Save scenario" onSubmit={async body=>{if(!changes.length)throw new Error('Add at least one scenario change.');setError(undefined);await save('/factories/'+id+'/scenarios',{...body,modifications:changes});setChanges([]);}}/><ErrorNotice error={error}/></Panel>}</>;
}
