import { useState } from 'react';
import { Link } from 'react-router-dom';
import type { ActionOut, VerificationPeriodOut } from '../../api/contracts';
import { useSession } from '../../hooks/useSession';
import { Panel, Resource, Rows, Value, RecordForm, useResource, useSave } from '../../components/platform/shared';
import { Note } from '../../components/ui/common';
function Verification({action}: {action:ActionOut}) {
  const query=useResource<VerificationPeriodOut[]>('/actions/'+action.id+'/verification'),save=useSave(),{can}=useSession(),[period,setPeriod]=useState<VerificationPeriodOut|null>(null);
  return <><Panel title="Measurement & verification"><Resource query={query}>{rows=><Rows rows={rows} columns={['period_start','period_end','status','results']} caption="Verification periods" onOpen={setPeriod}/>}</Resource>{can('factory:write')&&<RecordForm schema="VerificationPeriodIn" fields={{period_start:{},period_end:{},notes:{type:'textarea'}}} submit="Create verification period" onSubmit={async body=>setPeriod(await save<VerificationPeriodOut>('/actions/'+action.id+'/verification',body))}/>}</Panel>{period&&<Panel title="Verification results"><Value value={period}/>{can('factory:write')&&<RecordForm schema="VerificationResultIn" fields={{metric:{},unit:{},baseline_value:{},expected_value:{},actual_value:{},confidence:{options:['low','medium','high']},assumptions:{type:'textarea'}}} submit="Add measured result" onSubmit={async body=>setPeriod(await save<VerificationPeriodOut>('/verification/'+period.id+'/results',[body]))}/>}<Note>Achievement is returned by the service. Link supporting bills, meter photos and audit notes to this action in the Evidence section.</Note></Panel>}</>;
}
export default function Tracker({id}: {id:string}) {
  const query=useResource<ActionOut[]>('/factories/'+id+'/actions'),[selected,setSelected]=useState<ActionOut|null>(null),save=useSave(),{can}=useSession();
  return <><Panel title="Implementation tracker"><Resource query={query}>{rows=><Rows rows={rows} columns={['name','status','expected_abatement_tco2e','actual_abatement_tco2e','expected_capex_inr','actual_capex_inr','target_date']} onOpen={setSelected} caption="Actions"/>}</Resource></Panel>{selected&&<><Panel title={selected.name}><Value value={selected}/><Link className="button" to={'/marketplace?factory='+id+'&intervention='+encodeURIComponent(selected.intervention_id)+'&action='+selected.id}>Find a provider for this action</Link>{can('factory:write')&&<RecordForm key={selected.id} schema="ActionPatch" initial={selected} fields={{status:{options:['PROPOSED','SELECTED','RFQ','APPROVED','IMPLEMENTING','COMPLETED','VERIFYING','VERIFIED','REJECTED']},target_date:{},actual_abatement_tco2e:{},actual_capex_inr:{},actual_annual_benefit_inr:{},notes:{type:'textarea',help:selected.was_blocked?'This action was blocked. Document the reviewed reason before changing its status.':''},rejected_reason:{type:'textarea'}}} submit="Update action" onSubmit={async body=>setSelected(await save<ActionOut>('/actions/'+selected.id,body,'PATCH'))}/>}</Panel><Verification key={selected.id} action={selected}/></>}</>;
}
