import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { useSession } from '../hooks/useSession';
import { setSession, signIn, signOut, switchOrganization } from '../api/platform';
import { PageHeading, Note } from '../components/ui/common';
import { ActionButton, ErrorNotice, Panel, RecordForm } from '../components/platform/shared';
export default function Account() {
  const [register,setRegister]=useState(false), {session,identity,me}=useSession(), client=useQueryClient();
  return <div className="page-reveal platform-page"><PageHeading eyebrow="WORKSPACE / ACCOUNT" title="Your working space." description="Manage a connected organization and its factory records."/>{session?<Panel title={identity?.user.full_name||'Your account'}><ErrorNotice error={me.error}/><p>{identity?.user.email}</p><label className="form-field">Active organization<select value={identity?.active_organization_id||''} onChange={async e=>{await client.cancelQueries();await switchOrganization(e.target.value);client.removeQueries({predicate:q=>q.queryKey[0]==='private'});}}>{identity?.memberships.map(m=><option value={m.organization.id} key={m.organization.id}>{m.organization.name} · {m.role}</option>)}</select></label><div className="platform-toolbar"><Link className="button" to="/workspace">Open workspace</Link><ActionButton onClick={async()=>{await client.cancelQueries();try {await signOut();}finally{setSession(null);client.removeQueries({predicate:q=>q.queryKey[0]==='private'});}}}>Sign out</ActionButton></div></Panel>:<Panel title={register?'Create your account':'Sign in'}><RecordForm key={String(register)} schema={register?'RegisterRequest':'LoginRequest'} fields={{...(register?{full_name:{},organization_name:{required:true},organization_kind:{options:['manufacturer','provider']}}:{}),email:{},password:{type:'password'}}} submit={register?'Create account':'Sign in'} onSubmit={async values=>{await client.cancelQueries();client.removeQueries({predicate:q=>q.queryKey[0]==='private'});await signIn(values,register);}}/><button className="text-button" onClick={()=>setRegister(!register)}>{register?'Already registered? Sign in':'New here? Create an account'}</button></Panel>}<Note>The existing demonstration dashboard remains available. Connected records are stored by your configured PRANGARA service. Session credentials are kept in this tab’s session storage.</Note></div>;
}
