import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import type { ProviderOut, ProviderMatch, ProviderServiceOut, MaterialListingOut, RFQOut, QuoteComparison, FactorySummary, ActionOut } from '../api/contracts';
import { useSession } from '../hooks/useSession';
import { PageHeading, Note } from '../components/ui/common';
import { Access, ActionButton, Panel, RecordForm, Resource, Rows, Value, useResource, useSave } from '../components/platform/shared';
const providerTypes=['equipment_seller','installation_contractor','esco','energy_auditor','recycled_material_supplier','recycler','transporter','process_consultant','maintenance_company','shared_capacity_provider'];
function ProviderDetail({provider}: {provider:ProviderOut}) {
  const services=useResource<ProviderServiceOut[]>('/providers/'+provider.id+'/services',true),{can}=useSession(),save=useSave();
  return <Panel title={provider.name}><Value value={provider}/><Resource query={services}>{rows=><Rows rows={rows} columns={['name','category','indicative_price_inr','price_basis','warranty_months','lead_time_days']} caption="Services"/>}</Resource>{can('platform:admin')&&provider.verification_status!=='verified'&&<ActionButton onClick={()=>save('/providers/'+provider.id+'/verify')}>Verify after human review</ActionButton>}<Note>Verification, ratings and service coverage are reported by the service. Demo seed listings are explicitly identified.</Note></Panel>;
}
function Directory({factory,intervention}: {factory:string;intervention:string}) {
  const [type,setType]=useState(''),[state,setState]=useState(''),[verified,setVerified]=useState(false),[selected,setSelected]=useState<ProviderOut|null>(null);
  const query=useResource<ProviderOut[]>('/providers?limit=200&provider_type='+encodeURIComponent(type)+'&state='+encodeURIComponent(state)+'&verified_only='+verified,true),matches=useResource<ProviderMatch[]>(factory&&intervention?'/providers/match?factory_id='+encodeURIComponent(factory)+'&intervention_id='+encodeURIComponent(intervention):null);
  return <><Panel title="Provider directory"><div className="form-grid"><label className="form-field">Provider type<select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{providerTypes.map(t=><option key={t}>{t}</option>)}</select></label><label className="form-field">State<input value={state} onChange={e=>setState(e.target.value)}/></label><label><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/> Verified only</label></div><Resource query={query}>{rows=><Rows rows={rows} columns={['name','provider_type','state','verification_status','rating','typical_lead_time_days','is_demo_seed']} onOpen={setSelected} caption="Providers"/>}</Resource></Panel>{factory&&intervention&&<Panel title="Matches for this intervention"><Resource query={matches}>{rows=><>{!rows.length&&<p>No matching providers were returned for this intervention.</p>}{rows.map(m=><article className="platform-extracted" key={m.provider.id}><button className="text-button" onClick={()=>setSelected(m.provider)}>{m.provider.name} ↗</button><Value value={{score:m.score,reasons:m.reasons,distance_km:m.distance_km,indicative_price_inr:m.indicative_price_inr}}/></article>)}</>}</Resource></Panel>}{selected&&<ProviderDetail key={selected.id} provider={selected}/>}</>;
}
function Materials() {
  const [mode,setMode]=useState('balanced'),[state,setState]=useState(''),query=useResource<MaterialListingOut[]>('/materials?limit=200&mode='+mode+(state?'&state='+encodeURIComponent(state):''),true);
  return <Panel title="Carbon-aware material sourcing"><div className="form-grid"><label className="form-field">Ranking<select value={mode} onChange={e=>setMode(e.target.value)}><option value="balanced">Balanced cost and carbon</option><option value="cheapest">Lowest price</option><option value="lowest_carbon">Lowest embodied carbon</option></select></label><label className="form-field">State<input value={state} onChange={e=>setState(e.target.value)}/></label></div><Resource query={query}>{rows=><Rows rows={rows} columns={['name','provider_name','grade','recycled_content_pct','embodied_tco2e_per_t','embodied_source','price_inr_per_t','moq_t','stock_t','certifications','is_demo_seed']} caption="Materials"/>}</Resource><Note>Rankings come from the service. Check the material specification, source and certification before procurement. Transport emissions and delivered cost are not included unless explicitly supplied.</Note></Panel>;
}
function QuoteDetail({rfq,provider}: {rfq:RFQOut;provider:boolean}) {
  const compare=useResource<QuoteComparison>(provider?null:'/rfqs/'+rfq.id+'/compare'),save=useSave(),{can}=useSession();
  return <Panel title={rfq.title}><Value value={{status:rfq.status,needed_by:rfq.needed_by,scope_of_work:rfq.scope_of_work,shared_context:rfq.shared_context}}/>{provider?<RecordForm schema="QuoteCreate" fields={{price_inr:{},installation_included:{},installation_inr:{},annual_opex_delta_inr:{},warranty_months:{},delivery_days:{},validity_days:{},notes:{type:'textarea'}}} submit="Submit quote to this request" onSubmit={body=>save('/rfqs/'+rfq.id+'/quotes',body)}/>:<Resource query={compare}>{c=><><Note>{c.note}</Note><Value value={{engine_estimate:c.engine_estimate}}/><Rows rows={c.quotes} columns={['provider_name','price_inr','installation_included','installation_inr','annual_opex_delta_inr','warranty_months','delivery_days','validity_days','revised_payback_yrs','revised_lcoa_inr_per_tco2e','status']} caption="Quote comparison"/>{can('marketplace:write')&&!c.rfq.accepted_quote_id&&c.quotes.filter(q=>q.status==='SUBMITTED'||q.status==='SHORTLISTED').map(q=><details key={q.id}><summary>Review selection: {q.provider_name}</summary><p>Accepting this quote records the selected provider and price for this request.</p><ActionButton onClick={()=>save('/quotes/'+q.id+'/accept')}>Accept {q.provider_name} quote</ActionButton></details>)}</>}</Resource>}</Panel>;
}
function Requests({factory,intervention,action}: {factory:string;intervention:string;action:string}) {
  const {can}=useSession(),provider=can('rfq:quote'),query=useResource<RFQOut[]>('/rfqs'+(!provider&&factory?'?factory_id='+encodeURIComponent(factory):'')),providers=useResource<ProviderOut[]>('/providers?limit=200',true),[selected,setSelected]=useState<RFQOut|null>(null),[invited,setInvited]=useState<string[]>([]),save=useSave();
  return <Access><Panel title={provider?'Invited quote requests':'Your quote requests'}><Resource query={query}>{rows=><Rows rows={rows} columns={['title','status','needed_by','quote_count','created_at']} caption="Quote requests" onOpen={setSelected}/>}</Resource></Panel>{selected&&<QuoteDetail key={selected.id} rfq={selected} provider={provider}/>} {!provider&&can('marketplace:write')&&factory&&intervention&&<Panel title="Request implementation quotes"><p>Select the providers who should receive this request. Only the backend’s limited project context is shared.</p><fieldset><legend>Invite providers</legend>{providers.data?.map(p=><label className="platform-check" key={p.id}><input type="checkbox" checked={invited.includes(p.id)} onChange={e=>setInvited(e.target.checked?[...invited,p.id]:invited.filter(x=>x!==p.id))}/>{p.name} · {p.verification_status}</label>)}</fieldset><RecordForm schema="RFQCreate" fields={{title:{},scope_of_work:{type:'textarea'},needed_by:{}}} submit="Create request and invite selected providers" onSubmit={async body=>{if(!invited.length)throw new Error('Select at least one provider.');setSelected(await save<RFQOut>('/rfqs',{...body,factory_id:factory,intervention_id:intervention,...(action?{action_id:action}:{}),provider_ids:invited}));}}/></Panel>}</Access>;
}
function ProviderWorkspace() {
  const {identity}=useSession(),query=useResource<ProviderOut[]>('/providers?limit=200',true),save=useSave();
  const own=query.data?.find(p=>p.organization_id===identity?.active_organization_id);
  return <Access><Panel title="Your provider profile">{query.isPending?<p>Loading provider profile…</p>:own?<Value value={own}/>:<RecordForm schema="ProviderCreate" fields={{name:{},provider_type:{options:providerTypes},description:{type:'textarea'},contact_email:{type:'email'},contact_phone:{},website:{},state:{},district:{},service_states:{},service_radius_km:{},certifications:{},typical_lead_time_days:{}}} submit="Create provider profile" onSubmit={body=>save('/providers',body)}/>}</Panel>{own&&<><Panel title="Add a service"><RecordForm schema="ProviderServiceIn" fields={{name:{},category:{options:['energy','process','material','waste','logistics']},description:{type:'textarea'},intervention_ids:{help:'One engine intervention ID per line.'},indicative_price_inr:{},price_basis:{},warranty_months:{},lead_time_days:{}}} submit="Publish service" onSubmit={body=>save('/providers/'+own.id+'/services',body)}/></Panel><Panel title="Add a material listing"><RecordForm schema="MaterialListingIn" fields={{name:{},material_key:{},grade:{},recycled_content_pct:{},embodied_factor_key:{},embodied_tco2e_per_t:{},embodied_source:{help:'A carbon figure requires its source.'},price_inr_per_t:{},moq_t:{},stock_t:{},certifications:{},state:{}}} submit="Publish material listing" onSubmit={body=>save('/materials',body)}/></Panel></>}</Access>;
}
export default function Marketplace() {
  const [params,setParams]=useSearchParams(),[tab,setTab]=useState('Providers'),{can}=useSession(),factory=params.get('factory')||'',intervention=params.get('intervention')||'',action=params.get('action')||'';
  const factories=useResource<FactorySummary[]>(can('factory:read')?'/factories?limit=200':null),actions=useResource<ActionOut[]>(factory&&can('factory:read')?'/factories/'+factory+'/actions':null);
  return <div className="page-reveal platform-page"><PageHeading eyebrow="WORKSPACE / MARKETPLACE" title="Make the next move." description="Find implementation support and compare cost with carbon."/>{can('factory:read')&&<Panel title="Project context"><div className="form-grid"><label className="form-field">Factory<select value={factory} onChange={e=>setParams({factory:e.target.value})}><option value="">Select factory…</option>{factories.data?.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label className="form-field">Intervention<select value={action} onChange={e=>{const a=actions.data?.find(x=>x.id===e.target.value);setParams({factory,...(a?{action:a.id,intervention:a.intervention_id}:{})});}}><option value="">Select action…</option>{actions.data?.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div></Panel>}<nav className="platform-tabs" aria-label="Marketplace sections">{['Providers','Materials','Quote requests',...(can('provider:manage')?['My services']:[])].map(t=><button key={t} aria-pressed={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>{tab==='Providers'?<Directory factory={factory} intervention={intervention}/>:tab==='Materials'?<Materials/>:tab==='Quote requests'?<Requests factory={factory} intervention={intervention} action={action}/>:<ProviderWorkspace/>}</div>;
}
