# Builds the standalone PRANGARA companion APK.
#
# `apps/mobile/android` is generated by `expo prebuild` and is not committed,
# so every build setting that has to survive a regeneration lives here rather
# than in a file inside that folder.
#
#   powershell -ExecutionPolicy Bypass -File apps/mobile/scripts/build-apk.ps1
#
# The result is copied to the repository root as prangara-companion-release.apk,
# which is what the GitHub release carries.

param(
    [switch]$Clean,
    [string]$OutputName = "prangara-companion-release.apk"
)

$ErrorActionPreference = "Stop"

$mobileRoot = Split-Path -Parent $PSScriptRoot
$repoRoot = Split-Path -Parent (Split-Path -Parent $mobileRoot)
Set-Location $mobileRoot

Write-Output "== PRANGARA companion APK =="
Write-Output "mobile root: $mobileRoot"

# 1. Native project. Regenerated only when asked, because a clean prebuild
#    throws away the Gradle and CMake caches and costs several minutes.
if ($Clean -or -not (Test-Path "$mobileRoot\android\gradlew.bat")) {
    Write-Output "-- expo prebuild (android)"
    npx expo prebuild --platform android --clean
    if ($LASTEXITCODE -ne 0) { throw "expo prebuild failed" }
}

# 2. Tell Gradle where the SDK is. `expo prebuild --clean` writes a fresh
#    android/ without local.properties, and this machine has no ANDROID_HOME,
#    so resolve the SDK from the usual install locations and write it.
$localProps = Join-Path $mobileRoot "android\local.properties"
$sdkCandidates = @(
    $env:ANDROID_HOME,
    $env:ANDROID_SDK_ROOT,
    "$env:LOCALAPPDATA\Android\Sdk",
    "$env:USERPROFILE\AppData\Local\Android\Sdk",
    "C:\Android\Sdk"
) | Where-Object { $_ -and (Test-Path (Join-Path $_ "platform-tools")) }

if (-not $sdkCandidates) {
    throw "No Android SDK found. Install it, or set ANDROID_HOME."
}
$sdk = $sdkCandidates[0]
$sdkForGradle = $sdk.Replace('\', '\\')
if (-not (Test-Path $localProps) -or -not ((Get-Content $localProps -Raw) -match "sdk.dir")) {
    Set-Content -Path $localProps -Value "sdk.dir=$sdkForGradle" -Encoding ascii
}
$env:ANDROID_HOME = $sdk
$env:ANDROID_SDK_ROOT = $sdk
Write-Output "-- Android SDK: $sdk"

# 3. Ship ARM only. x86 and x86_64 exist for emulators; carrying them roughly
#    doubles the download for every real phone that will never load them.
$propsPath = "$mobileRoot\android\gradle.properties"
$props = Get-Content $propsPath -Raw
$armOnly = "reactNativeArchitectures=armeabi-v7a,arm64-v8a"
if ($props -notmatch [regex]::Escape($armOnly + "`n") -and $props -notmatch [regex]::Escape($armOnly + "`r")) {
    $props = $props -replace "reactNativeArchitectures=.*", $armOnly
    Set-Content -Path $propsPath -Value $props -Encoding utf8
    Write-Output "-- gradle.properties: $armOnly"
}

# 4. Assemble. Expo signs the release with the generated debug keystore unless a
#    release keystore is configured, which is fine for sideloading and is
#    stated in RELEASE.md.
Write-Output "-- gradlew assembleRelease"
Set-Location "$mobileRoot\android"
.\gradlew.bat :app:assembleRelease --no-daemon
if ($LASTEXITCODE -ne 0) { throw "gradle assembleRelease failed" }

$apk = "$mobileRoot\android\app\build\outputs\apk\release\app-release.apk"
if (-not (Test-Path $apk)) { throw "expected APK not found at $apk" }

$destination = Join-Path $repoRoot $OutputName
Copy-Item $apk $destination -Force

$size = [math]::Round((Get-Item $destination).Length / 1MB, 1)
$hash = (Get-FileHash $destination -Algorithm SHA256).Hash
Write-Output ""
Write-Output "APK:    $destination"
Write-Output "Size:   $size MB"
Write-Output "SHA256: $hash"
