/**
 * Shared API types.
 *
 * These mirror the backend Pydantic models, which own the contract
 * (task.md section 3). The authoritative schema is
 * `packages/contracts/openapi.json`, regenerated by
 * `python -m scripts.export_openapi`.
 *
 * No field here may be renamed or invented on this side. If the mobile app
 * needs a field the API does not return, the contract changes first.
 */

export type Band = { low: number; base: number; high: number };

export type DataState =
  | 'VERIFIED'
  | 'DOCUMENT-CONFIRMED'
  | 'DECLARED'
  | 'ESTIMATED'
  | 'MISSING'
  | 'STALE';

export type StreamKind = 'electricity' | 'fuel' | 'material' | 'waste' | 'freight';

export interface TokenResponse {
  access_token: string;
  refresh_token: string;
  token_type: string;
  expires_in: number;
}

export interface Organization {
  id: string;
  name: string;
  kind: string;
  state?: string | null;
  country?: string | null;
}

export interface Me {
  user: {
    id: string;
    email: string;
    full_name: string;
    phone?: string | null;
    is_active: boolean;
  };
  memberships: { organization: Organization; role: string; is_default: boolean }[];
  active_organization_id: string | null;
  is_platform_admin: boolean;
  permissions: string[];
}

export interface Sector {
  key: string;
  label: string;
  clusters: string[];
  demo_name?: string;
}

export interface Factory {
  id: string;
  organization_id: string;
  name: string;
  sector: string;
  subsector?: string | null;
  state?: string | null;
  district?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  created_at: string;
  updated_at: string;
  latest_assessment_id?: string | null;
  latest_assessed_at?: string | null;
  total_tco2e?: number | null;
  scope3_tco2e?: number | null;
  critical_leak_count?: number | null;
  cash_positive_benefit_inr?: number | null;
  open_action_count: number;
  data_quality_score?: number | null;
}

export interface ActivityRecordIn {
  stream_kind: StreamKind;
  factor_key?: string | null;
  label?: string | null;
  quantity: number;
  unit: string;
  period_start?: string | null;
  period_end?: string | null;
  data_state?: DataState;
  source_kind?: string;
  extraction_confidence?: number | null;
  unit_cost_inr?: number | null;
  notes?: string | null;
}

export interface ActivityRecord extends ActivityRecordIn {
  id: string;
  profile_id: string;
  factory_id: string;
  confirmed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface ExtractedField {
  field: string;
  value: number | string;
  unit?: string | null;
  confidence: number;
  evidence_text?: string | null;
  needs_confirmation: boolean;
}

export interface ConversationExtractResponse {
  extractor: 'llm' | 'rule_based';
  extractor_detail: string;
  fields: ExtractedField[];
  missing_fields: string[];
  follow_up_questions: string[];
  warnings: string[];
  requires_user_confirmation: boolean;
}

export interface DocumentExtractResponse {
  evidence_id: string;
  document_type?: string | null;
  extractor: 'ocr' | 'unavailable';
  extractor_detail: string;
  fields: ExtractedField[];
  suggested_activity_records: ActivityRecordIn[];
  period_start?: string | null;
  period_end?: string | null;
  requires_user_confirmation: boolean;
  warnings: string[];
}

export interface EquipmentExtractResponse {
  evidence_id?: string | null;
  extractor: 'ocr' | 'unavailable';
  extractor_detail: string;
  fields: ExtractedField[];
  required_questions: string[];
  requires_user_confirmation: boolean;
}

/** The engine payload. Shape owned by `backend/engine`. */
export interface AssessmentResult {
  headline: {
    total_tco2e: number;
    total_range: Band;
    uncertainty_pct: number;
    top_leak: string | null;
    top_leak_share_pct: number | null;
    top_leak_severity: string | null;
    peer_percentile: number | null;
    cash_positive_abatement_tco2e: number;
    cash_positive_abatement_pct: number;
    cash_positive_annual_benefit_inr: number;
    cash_positive_capex_inr: number;
    cash_positive_payback_months: number | null;
    quick_win_count: number;
    total_abatement_available_pct: number;
    statement: string;
  };
  footprint: {
    total_tco2e: number;
    total_range: Band;
    scope1_tco2e: number;
    scope2_tco2e: number;
    scope3_tco2e: number;
    scope_split_pct: { scope1: number; scope2: number; scope3: number };
    uncertainty_pct: number;
    intensities: Record<string, number>;
    grid_source: string;
    streams: {
      key: string;
      label: string;
      scope: number;
      tco2e: number;
      range: Band;
      share_pct: number;
      activity_qty: number;
      activity_unit: string;
      source: string;
    }[];
  };
  leaks: {
    leak_count: number;
    critical_count: number;
    peer_position: {
      metric_label: string;
      actual: number;
      p25: number;
      p50: number;
      p75: number;
      percentile: number;
    } | null;
    benchmark_source: string;
    benchmark_caveat: string;
    leaks: {
      stream_key: string;
      label: string;
      rule: string;
      severity: string;
      tco2e: number;
      share_pct: number;
      metric_label?: string | null;
      metric_unit?: string | null;
      actual?: number | null;
      p50?: number | null;
      p75?: number | null;
      percentile?: number | null;
      gap_to_median_tco2e: number;
      finding: string;
    }[];
  };
  recommendations: {
    count: number;
    total_abatement_available_tco2e: number;
    total_abatement_pct: number;
    recommendations: Recommendation[];
    blocked: { id: string; name: string; reason: string }[];
    portfolio: Record<string, PortfolioStats>;
    assumptions: Record<string, unknown>;
  };
  compliance: Record<string, unknown>;
  data_quality: {
    score: number;
    band: string;
    gaps: string[];
    notes: string[];
    plausibility_flags: string[];
  };
  versions: Record<string, string>;
  claim_boundary?: string;
}

export interface Recommendation {
  id: string;
  name: string;
  category: string;
  description: string;
  why: string;
  evidence: string;
  caveats: string[];
  difficulty: number;
  disruption_days: number;
  confidence: string;
  target_stream_label: string;
  abatement_tco2e: number;
  abatement_range: Band;
  abatement_pct_of_total: number;
  portfolio_abatement_tco2e: number;
  capex_inr: number;
  net_annual_benefit_inr: number;
  lcoa_inr_per_tco2e: number;
  payback_yrs: number | null;
  payback_months: number | null;
  npv_inr: number;
  cash_positive: boolean;
  physical_note: string;
  savings_model: string;
  substitution_capped: boolean;
  restriction_note: string;
}

export interface PortfolioStats {
  count: number;
  abatement_tco2e: number;
  abatement_pct: number;
  capex_inr: number;
  net_annual_benefit_inr: number;
  blended_payback_months: number | null;
  npv_inr: number;
}

export interface Assessment {
  id: string;
  factory_id: string;
  label?: string | null;
  is_baseline: boolean;
  created_at: string;
  total_tco2e?: number | null;
  scope1_tco2e?: number | null;
  scope2_tco2e?: number | null;
  scope3_tco2e?: number | null;
  leak_count?: number | null;
  critical_leak_count?: number | null;
  data_quality_score?: number | null;
  version_stamp: Record<string, string>;
  engine_profile?: Record<string, unknown>;
  result?: AssessmentResult;
}

export interface Action {
  id: string;
  factory_id: string;
  intervention_id: string;
  name: string;
  category?: string | null;
  target_stream?: string | null;
  status: string;
  expected_abatement_tco2e?: number | null;
  expected_capex_inr?: number | null;
  expected_annual_benefit_inr?: number | null;
  expected_payback_yrs?: number | null;
  expected_lcoa_inr_per_tco2e?: number | null;
  was_blocked: boolean;
  was_capped: boolean;
  restriction_note?: string | null;
  notes?: string | null;
}

export interface Evidence {
  id: string;
  evidence_type: string;
  title: string;
  filename: string;
  content_type: string;
  size_bytes: number;
  verification_status: string;
  created_at: string;
  download_url?: string | null;
  links: { target_type: string; target_id: string; role?: string | null }[];
}

export interface Notification {
  id: string;
  kind: string;
  severity: 'info' | 'warning' | 'critical';
  title: string;
  body?: string | null;
  deep_link?: string | null;
  factory_id?: string | null;
  created_at: string;
  read_at?: string | null;
}

export interface Health {
  status: string;
  app: string;
  version: string;
  environment: string;
  database: string;
  engine: {
    engine_version: string;
    sectors: number;
    interventions: number;
    factors: number;
  };
  counts: Record<string, number>;
  features: { postgres: boolean; object_storage: boolean; llm_intake: boolean };
}

export interface ApiErrorBody {
  code: string;
  message: string;
  details: Record<string, unknown>;
}
