import { useState } from 'react';
import type { ConversationExtractResponse, ConfirmIntakeRequest } from '../../api/contracts';
import { send } from '../../api/platform';
import { useSession } from '../../hooks/useSession';
import { Panel, RecordForm, Value, ErrorNotice, useSave, label } from '../../components/platform/shared';
import { Note } from '../../components/ui/common';
const profileKeys=new Set(['annual_output_t','annual_revenue_cr','employees','operating_days','shifts_per_day','export_share_pct','eu_export_share_pct','tariff_inr_per_kwh','discount_rate']);
export default function Intake({id}: {id:string}) {
  const [extracted,setExtracted]=useState<ConversationExtractResponse|null>(null),[error,setError]=useState<unknown>(),[pending,setPending]=useState(false),[done,setDone]=useState(false),save=useSave(),{can}=useSession();
  if (!can('factory:write')) return <Panel title="Intake"><p>Your role has read access. Ask a factory editor to confirm intake values.</p></Panel>;
  return <><Panel title="Tell us about the plant"><RecordForm schema="ConversationExtractRequest" fields={{message:{type:'textarea',help:'Include the quantity, unit and reporting period for each activity.'}}} submit="Extract proposed values" onSubmit={async body=>{setExtracted(await send<ConversationExtractResponse>('/intake/conversation/extract',{...body,factory_id:id}));setDone(false);}}/></Panel>{extracted&&<Panel title="Review before saving"><p>{extracted.extractor_detail}</p><Value value={extracted.warnings}/><form onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),body:ConfirmIntakeRequest={profile_updates:{},activity_records:[],source_kind:'conversation'};for (const [i,f] of extracted.fields.entries()) {if (!fd.has('include-'+i)) continue;const value=Number(fd.get('value-'+i));if(profileKeys.has(f.field)) body.profile_updates![f.field]=value;else if(f.field==='electricity_kwh')body.activity_records!.push({stream_kind:'electricity',quantity:value,unit:'kWh',data_state:'DECLARED'});else if(f.field.startsWith('fuel_'))body.activity_records!.push({stream_kind:'fuel',factor_key:f.field.slice(5),quantity:value,unit:f.unit||'',data_state:'DECLARED'});}if(!Object.keys(body.profile_updates!).length&&!body.activity_records!.length){setError(new Error('Select at least one supported field to confirm.'));return;}setPending(true);setError(undefined);try{await save('/intake/factories/'+id+'/confirm',body);setDone(true);}catch(err){setError(err);}finally{setPending(false);}}}>{extracted.fields.map((f,i)=>{const supported=profileKeys.has(f.field)||f.field==='electricity_kwh'||f.field.startsWith('fuel_');return <div className="platform-extracted" key={i}><label><input type="checkbox" name={'include-'+i} disabled={!supported||done}/> Confirm {label(f.field)}</label><label className="form-field">Proposed value · {f.unit||'unit not supplied'}<input name={'value-'+i} type="number" step="any" min="0" defaultValue={typeof f.value==='number'?f.value:''} required disabled={!supported||done}/></label><p>Confidence: {f.confidence} · Source: {f.evidence_text||'Not supplied'}</p>{!supported&&<p>Enter this field in the structured profile form.</p>}</div>;})}<ErrorNotice error={error}/><button className="button" disabled={pending||done}>{done?'Values confirmed':pending?'Saving…':'Confirm selected values'}</button></form><h3>Still needed</h3><Value value={extracted.follow_up_questions}/><Note>Confirmed activities are added to the current reporting period. Check existing records to avoid entering the same bill twice. Extraction does not calculate emissions.</Note></Panel>}</>;
}
