"""add_client_ref_and_shipments

Revision ID: b128a0883adb
Revises: b84529f609da
Create Date: 2026-09-12 16:41:01.042627
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b128a0883adb'
down_revision = 'b84529f609da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('vehicle_id_plate', sa.String(length=64), nullable=False),
    sa.Column('fleet_operator', sa.String(length=128), nullable=False),
    sa.Column('vehicle_class', sa.String(length=64), nullable=False),
    sa.Column('fuel_type', sa.String(length=64), nullable=False),
    sa.Column('payload_capacity_t', sa.Float(), nullable=False),
    sa.Column('current_location', sa.String(length=128), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lon', sa.Float(), nullable=True),
    sa.Column('route_capability', sa.String(length=256), nullable=False),
    sa.Column('well_to_wheel_factor_kgco2e_per_tkm', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data_mode', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_vehicles_status_location', ['status', 'current_location'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_vehicle_id_plate'), ['vehicle_id_plate'], unique=True)

    op.create_table('shipments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=True),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('origin_name', sa.String(length=128), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lon', sa.Float(), nullable=False),
    sa.Column('destination_name', sa.String(length=128), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lon', sa.Float(), nullable=False),
    sa.Column('payload_tonnes', sa.Float(), nullable=False),
    sa.Column('cargo_type', sa.String(length=128), nullable=False),
    sa.Column('earliest_pickup', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pooled_run_id', sa.String(length=64), nullable=True),
    sa.Column('assigned_vehicle_id', sa.String(length=32), nullable=True),
    sa.Column('selected_route_preset', sa.String(length=32), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('transit_hours', sa.Float(), nullable=True),
    sa.Column('cost_inr', sa.Float(), nullable=True),
    sa.Column('emissions_kgco2e', sa.Float(), nullable=True),
    sa.Column('tracking_metadata', sa.JSON(), nullable=False),
    sa.Column('client_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_client_ref'), ['client_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_factory_id'), ['factory_id'], unique=False)
        batch_op.create_index('ix_shipments_factory_status', ['factory_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_pooled_run_id'), ['pooled_run_id'], unique=False)

    with op.batch_alter_table('activity_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_ref', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_activity_records_client_ref'), ['client_ref'], unique=False)

    with op.batch_alter_table('evidence_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_ref', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_evidence_documents_client_ref'), ['client_ref'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_documents_client_ref'))
        batch_op.drop_column('client_ref')

    with op.batch_alter_table('activity_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_records_client_ref'))
        batch_op.drop_column('client_ref')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_pooled_run_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_organization_id'))
        batch_op.drop_index('ix_shipments_factory_status')
        batch_op.drop_index(batch_op.f('ix_shipments_factory_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_client_ref'))

    op.drop_table('shipments')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vehicle_id_plate'))
        batch_op.drop_index('ix_vehicles_status_location')
        batch_op.drop_index(batch_op.f('ix_vehicles_organization_id'))

    op.drop_table('vehicles')
    # ### end Alembic commands ###
