"""initial platform schema

Revision ID: b84529f609da
Revises: 
Create Date: 2026-09-12 07:48:25.507309
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b84529f609da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=True),
    sa.Column('scenario_id', sa.String(length=32), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('engine_profile', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('version_stamp', sa.JSON(), nullable=False),
    sa.Column('total_tco2e', sa.Float(), nullable=True),
    sa.Column('total_low_tco2e', sa.Float(), nullable=True),
    sa.Column('total_high_tco2e', sa.Float(), nullable=True),
    sa.Column('scope1_tco2e', sa.Float(), nullable=True),
    sa.Column('scope2_tco2e', sa.Float(), nullable=True),
    sa.Column('scope3_tco2e', sa.Float(), nullable=True),
    sa.Column('scope12_per_t', sa.Float(), nullable=True),
    sa.Column('electricity_kwh_per_t', sa.Float(), nullable=True),
    sa.Column('thermal_gj_per_t', sa.Float(), nullable=True),
    sa.Column('leak_count', sa.Integer(), nullable=True),
    sa.Column('critical_leak_count', sa.Integer(), nullable=True),
    sa.Column('cash_positive_abatement_tco2e', sa.Float(), nullable=True),
    sa.Column('cash_positive_benefit_inr', sa.Float(), nullable=True),
    sa.Column('cash_positive_capex_inr', sa.Float(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['factory_profiles.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_factory_id'), ['factory_id'], unique=False)
        batch_op.create_index('ix_assessments_factory_time', ['factory_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_organization_id'), ['organization_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('baseline_assessment_id', sa.String(length=32), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('modifications', sa.JSON(), nullable=False),
    sa.Column('latest_assessment_id', sa.String(length=32), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_factory_id'), ['factory_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('actor_label', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=48), nullable=False),
    sa.Column('object_id', sa.String(length=48), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index('ix_audit_object', ['object_type', 'object_id'], unique=False)
        batch_op.create_index('ix_audit_org_time', ['organization_id', 'created_at'], unique=False)

    op.create_table('factories',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('subsector', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('cluster', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('referred_by_org_id', sa.String(length=32), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['referred_by_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('factories', schema=None) as batch_op:
        batch_op.create_index('ix_factories_org_active', ['organization_id', 'archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_factories_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_factories_sector'), ['sector'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_membership')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('providers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider_type', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=24), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('service_states', sa.JSON(), nullable=False),
    sa.Column('service_radius_km', sa.Float(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('verified_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('typical_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('accepting_work', sa.Boolean(), nullable=False),
    sa.Column('is_demo_seed', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index('ix_providers_type_state', ['provider_type', 'state'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('ix_refresh_user_active', ['user_id', 'revoked_at'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('origin_assessment_id', sa.String(length=32), nullable=True),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('intervention_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=True),
    sa.Column('target_stream', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('expected_abatement_tco2e', sa.Float(), nullable=True),
    sa.Column('expected_capex_inr', sa.Float(), nullable=True),
    sa.Column('expected_annual_benefit_inr', sa.Float(), nullable=True),
    sa.Column('expected_payback_yrs', sa.Float(), nullable=True),
    sa.Column('expected_lcoa_inr_per_tco2e', sa.Float(), nullable=True),
    sa.Column('engine_snapshot', sa.JSON(), nullable=False),
    sa.Column('actual_abatement_tco2e', sa.Float(), nullable=True),
    sa.Column('actual_capex_inr', sa.Float(), nullable=True),
    sa.Column('actual_annual_benefit_inr', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('was_blocked', sa.Boolean(), nullable=False),
    sa.Column('was_capped', sa.Boolean(), nullable=False),
    sa.Column('restriction_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['origin_assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'intervention_id', name='uq_action_factory_intervention')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_factory_id'), ['factory_id'], unique=False)
        batch_op.create_index('ix_actions_factory_status', ['factory_id', 'status'], unique=False)

    op.create_table('compliance_cases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('assessment_id', sa.String(length=32), nullable=True),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_pack', sa.String(length=48), nullable=False),
    sa.Column('rule_pack_version', sa.String(length=32), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('flow_state', sa.String(length=32), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('required_evidence', sa.JSON(), nullable=False),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('reviewer_user_id', sa.String(length=32), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_cases', schema=None) as batch_op:
        batch_op.create_index('ix_cases_factory_status', ['factory_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_cases_factory_id'), ['factory_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('factory_id', sa.String(length=32), nullable=True),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index('ix_events_status_time', ['status', 'occurred_at'], unique=False)
        batch_op.create_index('ix_events_tenant_type', ['organization_id', 'event_type'], unique=False)

    op.create_table('evidence_documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=True),
    sa.Column('uploaded_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verified_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction', sa.JSON(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_documents_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_documents_factory_id'), ['factory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_documents_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_evidence_factory_type', ['factory_id', 'evidence_type'], unique=False)
        batch_op.create_index('ix_evidence_org_hash', ['organization_id', 'content_sha256'], unique=False)

    op.create_table('factory_access',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('granted_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'factory_id', name='uq_factory_access')
    )
    with op.batch_alter_table('factory_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factory_access_factory_id'), ['factory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_factory_access_user_id'), ['user_id'], unique=False)

    op.create_table('factory_sites',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('factory_sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factory_sites_factory_id'), ['factory_id'], unique=False)

    op.create_table('material_listings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('material_key', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('grade', sa.String(length=120), nullable=True),
    sa.Column('recycled_content_pct', sa.Float(), nullable=True),
    sa.Column('embodied_factor_key', sa.String(length=64), nullable=True),
    sa.Column('embodied_tco2e_per_t', sa.Float(), nullable=True),
    sa.Column('embodied_source', sa.String(length=255), nullable=True),
    sa.Column('price_inr_per_t', sa.Float(), nullable=True),
    sa.Column('moq_t', sa.Float(), nullable=True),
    sa.Column('stock_t', sa.Float(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo_seed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_listings_material_key'), ['material_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_listings_provider_id'), ['provider_id'], unique=False)

    op.create_table('provider_services',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intervention_ids', sa.JSON(), nullable=False),
    sa.Column('indicative_price_inr', sa.Float(), nullable=True),
    sa.Column('price_basis', sa.String(length=64), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_services_provider_id'), ['provider_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=True),
    sa.Column('asset_type', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('rated_power_kw', sa.Float(), nullable=True),
    sa.Column('rated_capacity', sa.Float(), nullable=True),
    sa.Column('capacity_unit', sa.String(length=32), nullable=True),
    sa.Column('efficiency_pct', sa.Float(), nullable=True),
    sa.Column('year_installed', sa.Integer(), nullable=True),
    sa.Column('energy_type', sa.String(length=32), nullable=True),
    sa.Column('fuel_factor_key', sa.String(length=64), nullable=True),
    sa.Column('operating_hours_per_year', sa.Float(), nullable=True),
    sa.Column('load_factor', sa.Float(), nullable=True),
    sa.Column('maintenance_status', sa.String(length=32), nullable=True),
    sa.Column('estimated_annual_kwh', sa.Float(), nullable=True),
    sa.Column('estimated_annual_tco2e', sa.Float(), nullable=True),
    sa.Column('estimate_basis', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('data_state', sa.String(length=24), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['factory_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_factory_id'), ['factory_id'], unique=False)

    op.create_table('corrective_actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_user_id', sa.String(length=32), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['compliance_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corrective_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corrective_actions_case_id'), ['case_id'], unique=False)

    op.create_table('evidence_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'target_type', 'target_id', name='uq_evidence_link')
    )
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_link_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_evidence_id'), ['evidence_id'], unique=False)

    op.create_table('factory_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('annual_output_t', sa.Float(), nullable=False),
    sa.Column('output_unit', sa.String(length=32), nullable=False),
    sa.Column('annual_revenue_cr', sa.Float(), nullable=False),
    sa.Column('employees', sa.Integer(), nullable=False),
    sa.Column('operating_days', sa.Integer(), nullable=True),
    sa.Column('shifts_per_day', sa.Integer(), nullable=True),
    sa.Column('export_share_pct', sa.Float(), nullable=False),
    sa.Column('eu_export_share_pct', sa.Float(), nullable=False),
    sa.Column('tariff_inr_per_kwh', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('field_states', sa.JSON(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['factory_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('factory_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factory_profiles_factory_id'), ['factory_id'], unique=False)
        batch_op.create_index('ix_profiles_factory_period', ['factory_id', 'period_start'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('factory_id', sa.String(length=32), nullable=True),
    sa.Column('event_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('deep_link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_unread', ['user_id', 'read_at'], unique=False)

    op.create_table('rfqs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('action_id', sa.String(length=32), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('intervention_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('scope_of_work', sa.Text(), nullable=True),
    sa.Column('shared_context', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_quote_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.create_index('ix_rfq_factory_status', ['factory_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfqs_factory_id'), ['factory_id'], unique=False)

    op.create_table('verification_periods',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('action_id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('baseline_assessment_id', sa.String(length=32), nullable=True),
    sa.Column('actual_assessment_id', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('normalisation', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['actual_assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['baseline_assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_periods_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_periods_factory_id'), ['factory_id'], unique=False)

    op.create_table('activity_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('stream_kind', sa.String(length=24), nullable=False),
    sa.Column('factor_key', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('data_state', sa.String(length=24), nullable=False),
    sa.Column('source_kind', sa.String(length=24), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('confirmed_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unit_cost_inr', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['factory_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_records', schema=None) as batch_op:
        batch_op.create_index('ix_activity_profile_stream', ['profile_id', 'stream_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_records_factory_id'), ['factory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_records_profile_id'), ['profile_id'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rfq_id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('submitted_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('price_inr', sa.Float(), nullable=False),
    sa.Column('installation_included', sa.Boolean(), nullable=False),
    sa.Column('installation_inr', sa.Float(), nullable=True),
    sa.Column('annual_opex_delta_inr', sa.Float(), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('revised_payback_yrs', sa.Float(), nullable=True),
    sa.Column('revised_lcoa_inr_per_tco2e', sa.Float(), nullable=True),
    sa.Column('comparison', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_demo_seed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_rfq_id'), ['rfq_id'], unique=False)
        batch_op.create_index('ix_quotes_rfq_status', ['rfq_id', 'status'], unique=False)

    op.create_table('rfq_invites',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rfq_id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfq_invites', schema=None) as batch_op:
        batch_op.create_index('ix_rfq_invite_provider', ['provider_id', 'rfq_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfq_invites_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfq_invites_rfq_id'), ['rfq_id'], unique=False)

    op.create_table('verification_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('period_id', sa.String(length=32), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('achievement_pct', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['verification_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.create_index('ix_verification_period_metric', ['period_id', 'metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_results_period_id'), ['period_id'], unique=False)

    op.create_table('implementation_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('quote_id', sa.String(length=32), nullable=False),
    sa.Column('rfq_id', sa.String(length=32), nullable=False),
    sa.Column('factory_id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('action_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('scheduled_start', sa.Date(), nullable=True),
    sa.Column('scheduled_end', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('final_cost_inr', sa.Float(), nullable=True),
    sa.Column('provider_notes', sa.Text(), nullable=True),
    sa.Column('manufacturer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    with op.batch_alter_table('implementation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_implementation_jobs_factory_id'), ['factory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_implementation_jobs_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_implementation_jobs_rfq_id'), ['rfq_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('implementation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_implementation_jobs_rfq_id'))
        batch_op.drop_index(batch_op.f('ix_implementation_jobs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_implementation_jobs_factory_id'))

    op.drop_table('implementation_jobs')
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_results_period_id'))
        batch_op.drop_index('ix_verification_period_metric')

    op.drop_table('verification_results')
    with op.batch_alter_table('rfq_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfq_invites_rfq_id'))
        batch_op.drop_index(batch_op.f('ix_rfq_invites_provider_id'))
        batch_op.drop_index('ix_rfq_invite_provider')

    op.drop_table('rfq_invites')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index('ix_quotes_rfq_status')
        batch_op.drop_index(batch_op.f('ix_quotes_rfq_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_provider_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('activity_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_records_profile_id'))
        batch_op.drop_index(batch_op.f('ix_activity_records_factory_id'))
        batch_op.drop_index('ix_activity_profile_stream')

    op.drop_table('activity_records')
    with op.batch_alter_table('verification_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_periods_factory_id'))
        batch_op.drop_index(batch_op.f('ix_verification_periods_action_id'))

    op.drop_table('verification_periods')
    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfqs_factory_id'))
        batch_op.drop_index('ix_rfq_factory_status')

    op.drop_table('rfqs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_unread')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('factory_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_profiles_factory_period')
        batch_op.drop_index(batch_op.f('ix_factory_profiles_factory_id'))

    op.drop_table('factory_profiles')
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_links_evidence_id'))
        batch_op.drop_index('ix_evidence_link_target')

    op.drop_table('evidence_links')
    with op.batch_alter_table('corrective_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrective_actions_case_id'))

    op.drop_table('corrective_actions')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_factory_id'))

    op.drop_table('assets')
    with op.batch_alter_table('provider_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_services_provider_id'))

    op.drop_table('provider_services')
    with op.batch_alter_table('material_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_listings_provider_id'))
        batch_op.drop_index(batch_op.f('ix_material_listings_material_key'))

    op.drop_table('material_listings')
    with op.batch_alter_table('factory_sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factory_sites_factory_id'))

    op.drop_table('factory_sites')
    with op.batch_alter_table('factory_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factory_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_factory_access_factory_id'))

    op.drop_table('factory_access')
    with op.batch_alter_table('evidence_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_org_hash')
        batch_op.drop_index('ix_evidence_factory_type')
        batch_op.drop_index(batch_op.f('ix_evidence_documents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_documents_factory_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_documents_content_sha256'))

    op.drop_table('evidence_documents')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_tenant_type')
        batch_op.drop_index('ix_events_status_time')
        batch_op.drop_index(batch_op.f('ix_events_correlation_id'))

    op.drop_table('events')
    with op.batch_alter_table('compliance_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_cases_factory_id'))
        batch_op.drop_index('ix_cases_factory_status')

    op.drop_table('compliance_cases')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index('ix_actions_factory_status')
        batch_op.drop_index(batch_op.f('ix_actions_factory_id'))

    op.drop_table('actions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_user_active')
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index('ix_providers_type_state')

    op.drop_table('providers')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('factories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factories_sector'))
        batch_op.drop_index(batch_op.f('ix_factories_organization_id'))
        batch_op.drop_index('ix_factories_org_active')

    op.drop_table('factories')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_time')
        batch_op.drop_index('ix_audit_object')
        batch_op.drop_index(batch_op.f('ix_audit_logs_correlation_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_factory_id'))

    op.drop_table('scenarios')
    op.drop_table('organizations')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_organization_id'))
        batch_op.drop_index('ix_assessments_factory_time')
        batch_op.drop_index(batch_op.f('ix_assessments_factory_id'))

    op.drop_table('assessments')
    # ### end Alembic commands ###
